[build]
  command = "npm run build"
  publish = "public"
  functions = "lambda"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"

[[redirects]]
  from = "/next"
  to = "/.netlify/functions/next"
  status = 301
  force = true

[[redirects]]
  from = "/previous"
  to = "/.netlify/functions/previous"
  status = 301
  force = true

[[redirects]]
  from = "/prev"
  to = "/.netlify/functions/previous"
  status = 301
  force = true